name: Publish Packages

on:
  push:
    branches:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci
      - run: npm run build

      # Publish GitHub Packages
      - name: Publish to GitHub Packages
        run: |
          echo "@yuemi-development:registry=https://npm.pkg.github.com" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" >> .npmrc
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Publish Forgejo
      - name: Publish to Forgejo Packages
        run: |
          echo "@yuemi-development:registry=https://git.yuemi.my.id/api/packages/YueMi-Development/npm/" > .npmrc
          echo "//git.yuemi.my.id/api/packages/YueMi-Development/npm/:_authToken=${NODE_AUTH_TOKEN}" >> .npmrc
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.FORGEJO_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true